### ISSUE TITLE
createAngDistributionSqlite fails

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em#17]
I would be very grateful if someone helps me to fix this. It worked in scipion 2.0 but not in scipion3/python3 after pwem split. It doesn't work in any plugin. 
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "/home/azazello/soft/scipion3/scipion-pyworkflow/pyworkflow/gui/form.py", line 1258, in _visualizeVar
    self.visualizeCallback(self.paramName)
  File "/home/azazello/soft/scipion3/scipion-pyworkflow/pyworkflow/viewer.py", line 266, in _visualizeParam
    views = self._getVisualizeDict()[paramName](paramName)
  File "/home/azazello/soft/scipion-plugins/scipion-em-cryoef/cryoef/viewers.py", line 113, in _showAngularDistribution
    plot = self._createAngDist2D()
  File "/home/azazello/soft/scipion-plugins/scipion-em-cryoef/cryoef/viewers.py", line 126, in _createAngDist2D
    self.createAngDistributionSqlite(sqliteFn, nparts,
AttributeError: 'CryoEFViewer' object has no attribute 'createAngDistributionSqlite'
```

**Comment by azazellochg** [comment]
Ok, the problem is that all plugin viewers should use a different base class:

class CryoEFViewer(EmProtocolViewer) rather than class CryoEFViewer(ProtocolViewer):
